-- Store new provider API keys encrypted by the application. Existing environment references remain valid.
alter table public.managed_providers add column if not exists priority integer not null default 100;
alter table public.managed_providers add column if not exists failover_enabled boolean not null default true;

alter table public.provider_credentials alter column secret_ref drop not null;
alter table public.provider_credentials add column if not exists source text not null default 'environment';
alter table public.provider_credentials add column if not exists encrypted_api_key text;
alter table public.provider_credentials add column if not exists key_mask text;
alter table public.provider_credentials add column if not exists last_used_at timestamptz;
alter table public.provider_credentials add column if not exists failure_count integer not null default 0;
alter table public.provider_credentials add column if not exists last_failure_at timestamptz;
alter table public.provider_credentials add column if not exists disabled_at timestamptz;
alter table public.provider_credentials drop constraint if exists provider_credentials_source_check;
alter table public.provider_credentials add constraint provider_credentials_source_check check(source in('environment','database'));
alter table public.provider_credentials drop constraint if exists provider_credentials_source_values_check;
alter table public.provider_credentials add constraint provider_credentials_source_values_check check((source='environment' and secret_ref is not null and encrypted_api_key is null) or (source='database' and encrypted_api_key is not null and key_mask is not null));
create index if not exists managed_providers_priority_idx on public.managed_providers(enabled,priority,id);
create index if not exists provider_credentials_runtime_idx on public.provider_credentials(provider_id,enabled,priority,id);
create index if not exists provider_credentials_source_idx on public.provider_credentials(source,enabled);

-- Credentials are never selected directly from the browser. Safe metadata is exposed through an admin-only RPC.
revoke all on table public.provider_credentials from anon,authenticated;
create or replace function public.admin_list_provider_credentials_metadata(p_provider_id uuid default null)
returns table(id uuid,provider_id uuid,provider_name text,label text,source text,key_mask text,secret_ref text,enabled boolean,priority integer,health_status public.credential_health,last_checked_at timestamptz,last_error text,last_used_at timestamptz,failure_count integer,last_failure_at timestamptz,disabled_at timestamptz,created_at timestamptz,updated_at timestamptz)
language plpgsql stable security definer set search_path='' as $$ begin if not public.is_admin() then raise exception 'FORBIDDEN'; end if; return query select c.id,c.provider_id,p.name,c.label,c.source,c.key_mask,case when c.source='environment' then c.secret_ref else null end,c.enabled,c.priority,c.health_status,c.last_checked_at,c.last_error,c.last_used_at,c.failure_count,c.last_failure_at,c.disabled_at,c.created_at,c.updated_at from public.provider_credentials c join public.managed_providers p on p.id=c.provider_id where p_provider_id is null or c.provider_id=p_provider_id order by p.priority,c.priority,c.created_at; end $$;
revoke all on function public.admin_list_provider_credentials_metadata(uuid) from public,anon;grant execute on function public.admin_list_provider_credentials_metadata(uuid) to authenticated;

create or replace function public.admin_create_provider_credential(p_provider_id uuid,p_label text,p_source text,p_secret_ref text,p_encrypted_api_key text,p_key_mask text,p_enabled boolean,p_priority integer,p_backend_secret text)
returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if not public.is_admin() or not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; if not exists(select 1 from public.managed_providers where id=p_provider_id) then raise exception 'NOT_FOUND'; end if; insert into public.provider_credentials(provider_id,label,source,secret_ref,encrypted_api_key,key_mask,enabled,priority,health_status,disabled_at) values(p_provider_id,p_label,p_source,p_secret_ref,p_encrypted_api_key,p_key_mask,p_enabled,p_priority,'unknown',case when p_enabled then null else now() end) returning id into v_id; return v_id; end $$;
revoke all on function public.admin_create_provider_credential(uuid,text,text,text,text,text,boolean,integer,text) from public,anon;grant execute on function public.admin_create_provider_credential(uuid,text,text,text,text,text,boolean,integer,text) to authenticated;

create or replace function public.admin_update_provider_credential(p_id uuid,p_label text,p_enabled boolean,p_priority integer,p_secret_ref text,p_encrypted_api_key text,p_key_mask text,p_backend_secret text)
returns void language plpgsql security definer set search_path='' as $$ begin if not public.is_admin() or not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; update public.provider_credentials set label=p_label,enabled=p_enabled,priority=p_priority,secret_ref=case when source='environment' and p_secret_ref is not null then p_secret_ref else secret_ref end,encrypted_api_key=case when source='database' and p_encrypted_api_key is not null then p_encrypted_api_key else encrypted_api_key end,key_mask=case when source='database' and p_key_mask is not null then p_key_mask else key_mask end,health_status=case when p_encrypted_api_key is not null or p_secret_ref is not null then 'unknown'::public.credential_health else health_status end,failure_count=case when p_encrypted_api_key is not null or p_secret_ref is not null then 0 else failure_count end,last_error=case when p_encrypted_api_key is not null or p_secret_ref is not null then null else last_error end,last_failure_at=case when p_encrypted_api_key is not null or p_secret_ref is not null then null else last_failure_at end,disabled_at=case when p_enabled then null else coalesce(disabled_at,now()) end where id=p_id; if not found then raise exception 'NOT_FOUND'; end if; end $$;
revoke all on function public.admin_update_provider_credential(uuid,text,boolean,integer,text,text,text,text) from public,anon;grant execute on function public.admin_update_provider_credential(uuid,text,boolean,integer,text,text,text,text) to authenticated;

create or replace function public.admin_delete_provider_credential(p_id uuid,p_backend_secret text) returns void language plpgsql security definer set search_path='' as $$ begin if not public.is_admin() or not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; delete from public.provider_credentials where id=p_id; if not found then raise exception 'NOT_FOUND'; end if; end $$;
revoke all on function public.admin_delete_provider_credential(uuid,text) from public,anon;grant execute on function public.admin_delete_provider_credential(uuid,text) to authenticated;

create or replace function public.admin_get_provider_credential_secret(p_id uuid,p_backend_secret text)
returns table(id uuid,provider_id uuid,source text,secret_ref text,encrypted_api_key text,base_url text,provider_type text)
language plpgsql security definer set search_path='' as $$ begin if not public.is_admin() or not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; return query select c.id,c.provider_id,c.source,c.secret_ref,c.encrypted_api_key,p.base_url,p.provider_type from public.provider_credentials c join public.managed_providers p on p.id=c.provider_id where c.id=p_id; end $$;
revoke all on function public.admin_get_provider_credential_secret(uuid,text) from public,anon;grant execute on function public.admin_get_provider_credential_secret(uuid,text) to authenticated;

drop function if exists public.api_runtime_credentials(uuid,uuid,text);
create function public.api_runtime_credentials(p_provider_id uuid,p_model_id uuid,p_backend_secret text)
returns table(id uuid,source text,secret_ref text,encrypted_api_key text,key_mask text,priority integer,base_url text,provider_type text,provider_failover_enabled boolean,credential_strategy text,remote_model_id text,input_cost_per_million numeric,output_cost_per_million numeric)
language plpgsql security definer set search_path='' as $$ begin if (select auth.uid()) is null then raise exception 'AUTH_REQUIRED'; end if; if not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; return query select c.id,c.source,c.secret_ref,c.encrypted_api_key,c.key_mask,c.priority,p.base_url,p.provider_type,p.failover_enabled,p.credential_strategy,m.remote_model_id,m.input_cost_per_million,m.output_cost_per_million from public.provider_credentials c join public.managed_providers p on p.id=c.provider_id join public.provider_models m on m.provider_id=p.id where c.provider_id=p_provider_id and m.id=p_model_id and c.enabled and p.enabled and m.enabled order by c.priority,c.created_at limit 8; end $$;
revoke all on function public.api_runtime_credentials(uuid,uuid,text) from public,anon;grant execute on function public.api_runtime_credentials(uuid,uuid,text) to authenticated;

create or replace function public.record_provider_credential_attempt(p_credential_id uuid,p_success boolean,p_status_code integer,p_error_code text,p_latency_ms integer,p_backend_secret text)
returns void language plpgsql security definer set search_path='' as $$ begin if (select auth.uid()) is null then raise exception 'AUTH_REQUIRED'; end if; if not private.backend_secret_valid(p_backend_secret) then raise exception 'FORBIDDEN'; end if; update public.provider_credentials set last_checked_at=now(),last_used_at=case when p_success then now() else last_used_at end,health_status=case when p_success then 'healthy'::public.credential_health when p_status_code in(401,403) then 'unhealthy'::public.credential_health else 'degraded'::public.credential_health end,failure_count=case when p_success then 0 else failure_count+1 end,last_failure_at=case when p_success then last_failure_at else now() end,last_error=case when p_success then null else left(coalesce(p_error_code,'PROVIDER_ERROR'),200) end where id=p_credential_id; end $$;
revoke all on function public.record_provider_credential_attempt(uuid,boolean,integer,text,integer,text) from public,anon;grant execute on function public.record_provider_credential_attempt(uuid,boolean,integer,text,integer,text) to authenticated;
